[package]
name = "bench_codec"
version = "0.1.0"
edition = "2021"

[dependencies]
parquet = "51.0.0"
arrow = "51.0.0"
quanta = "0.12.3"
csv = "1.3.0"
serde ={version = "1.0.199",features = ["derive"]}
bytes = "1.6.0"
